services:
  postgres:
    image: postgres:15
    container_name: flowcare_db
    restart: always
    environment:
      POSTGRES_USER: flowcare
      POSTGRES_PASSWORD: flowcare123
      POSTGRES_DB: flowcare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: